# Generated by Django 5.2.1 on 2025-05-27 18:11
# Generated by Django 5.2.1 on 2025-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcomment',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='reportproject',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='reportproject',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportComment',
        ),
        migrations.DeleteModel(
            name='ReportProject',
        ),
    ]
