# Generated by Django 5.2.1 on 2025-05-27 18:11
# Generated by Django 5.2.1 on 2025-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tag Name'),
        ),
    ]
