# Generated by Django 5.2.1 on 2025-05-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
    ]
