from django.db import models
from accounts.models import ProfileUser
from project.models import Project

class Comment(models.Model):
    user_id = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    parent_id = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies', verbose_name="Parent Comment")
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return f"Comment by {self.user} on {self.project}"
    
#         Column     |           Type           | Collation | Nullable |             Default              
# ---------------+--------------------------+-----------+----------+----------------------------------
#  id            | bigint                   |           | not null | generated by default as identity
#  comment       | text                     |           | not null | 
#  created_date  | timestamp with time zone |           | not null | 
#  parent_id_id  | bigint                   |           |          | 
#  project_id_id | bigint                   |           | not null | 
#  user_id_id    | bigint                   |           | not null | 