# Generated by Django 5.2.1 on 2025-05-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_donations',
        ),
    ]
